In [1]:
import re
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import ast

In [36]:
location = "./IP_Only/"

#"./Documents/GitHub/UncertainTarget/EnumX_RowCol2ndStage/TestInstances/"
directory = os.fsencode(location)

# def importSet(filename, setRow, setLabel):
df_IP = pd.DataFrame(columns=('dataSet', 'ins','theta_IP', 'totalTime_IP', 't_RowGen_IP', 'n_RowGen_IP', 't_ColGen_IP','n_ColGen_IP'))
# location = "Documents/GitHub/UncertainTarget/EnumX_RowCol2ndStage/TestInstances/p_Instances_Output/"
allSets = []
k = 0
for file in os.listdir(directory):
    filename = os.fsdecode(file) 
#     print(filename)
    if filename.startswith('O_'):
        filePath = os.path.join(location, filename)
#         print(filePath)
        thisFile = open(filePath, "r")
          # remove /n at the end of each line
        lines_E = thisFile.readlines()
        thisFile.close()
        r = 0
        df_row = [0 for i in range(8)]
        for index, line in enumerate(lines_E):
            lines_E[index] = line.strip()
        for line in lines_E:
#             print(line)
            line = line.replace(', ', ',')
            line = line.replace('; ', ' ')
            elem = line.split(' = ')
            if elem[0] == "dataSet":
#                 
                df_row[0] = elem[1]
            elif elem[0] == "ins":
                df_row[1] = elem[1]
            elif elem[0] == "theta":
                df_row[2] = elem[1]
            elif elem[0] == "totalTime":
                df_row[3] = elem[1]
            elif elem[0] == "t_RowGen":
                df_row[4] = elem[1]
            elif elem[0] == "n_RowGen":
                df_row[5] = elem[1]
            elif elem[0] == "t_ColGen":
                df_row[6] = elem[1]
            elif elem[0] == "n_ColGen":
                df_row[7] = elem[1]
                        
#             r = r+1
#         print(df_row)
        k=k+1
        df_IP.loc[k] = df_row
for colName in ['ins','theta_IP', 'totalTime_IP', 't_RowGen_IP', 'n_RowGen_IP', 't_ColGen_IP','n_ColGen_IP']:
    df_IP[colName] = pd.to_numeric(df_IP[colName])
#         print(df_E)
# display(df_E.style.format({'RootOptGap': '{:,.1%}'.format}))
# display()
df_IP.loc[df_IP.totalTime_IP <= 3600, 'class'] = "E"
df_IP.loc[df_IP.totalTime_IP > 3600, 'class'] = "H"
df_IP

# df_IP.groupby(['dataSet', 'class'], as_index=False).count()
# df_IP.groupby(['dataSet'], as_index=False).aggregate({'totalTime_IP':np.average,'t_RowGen_IP':np.average,'t_ColGen_IP':np.average, 't_ColGen_IP':np.average })
# df_time = df_IP[['dataSet', 'ins', 'totalTime_IP']]
# df_time

,dataSet,ins,theta_IP,totalTime_IP,t_RowGen_IP,n_RowGen_IP,t_ColGen_IP,n_ColGen_IP,class
1,N30_d10_,13,0.033426,1428.257568,1388.782731,94,6.590644,80,E
2,N30_d10_,60,0.002358,64.885325,28.643936,27,3.691340,19,E
3,N30_d10_,6,0.000617,62.257446,26.526677,24,3.531471,18,E
4,N60_d10_,16,0.426883,3712.242432,3675.961859,14,3.477923,12,H
5,N30_d10_,18,0.006732,584.030919,547.916334,19,3.568471,15,E
...,...,...,...,...,...,...,...,...,...
82,N30_d10_,46,0.000621,104.733857,68.417155,45,3.950127,34,E
83,N30_d10_,23,0.000340,137.143070,100.537819,53,4.271750,37,E
84,N30_d10_,50,0.002343,84.279092,48.106613,31,3.706029,23,E
85,N40_d10_,80,0.022000,1377.640459,1341.242060,24,3.758831,19,E
86,N60_d10_,48,0.136850,412.048270,376.191143,7,3.425770,7,E

In [43]:
location = "./IP_Only/"
df_Summary_SVI = pd.DataFrame()
df_Summary_SVI = df_IP.groupby(['dataSet', 'class'], as_index=False).size().reset_index(name='counts')

df_less1 = pd.DataFrame(columns=['dataSet', 'ins'])
filename = "LessThanAMinutes_IPOnly.txt"
filePath = os.path.join(location, filename)
#         print(filePath)
thisFile = open(filePath, "r")
  # remove /n at the end of each line
lines_E = thisFile.readlines()
thisFile.close()
k = 0
df_row = [0 for i in range(2)]
for index, line in enumerate(lines_E):
    lines_E[index] = line.strip()
#         if filename.startswith('O_N30_'):
#                 print(filename)
for line in lines_E:
#             if filename.startswith('O_N30_'):
#                 print(filename)
#     print(line)
    line = line.replace(' = ', ' ')
    line = line.replace('\t', ' ')
    elem = line.split(' ')
#     print(elem)
    df_row[0] = elem[1]
    df_row[1] = elem[3]
    k=k+1
#     print(df_row)
    df_less1.loc[k] = df_row
df_less1['ins'] = pd.to_numeric(df_less1['ins'])
#df.groupby(['col1', 'col2']).size()

# df_less1 = df_less1.groupby(['dataSet'],  as_index=False).size().reset_index(name='counts')

# df_Summary_SVI
df_less1['totalTime_IP'] = 1
df_less1

df_time = df_IP[['dataSet', 'ins', 'totalTime_IP']].append(df_less1, ignore_index=True)
df_time= df_time.sort_values(by=['dataSet','ins'])
# df_time= df_time.sort_values(by=['ins'])
df_time
# df_time[['dataSet']==]

# df_time = pd.merge(df_time, df_less1,  how='left', left_on=['dataSet','ins'], right_on = ['dataSet','ins'])

     dataSet  ins  totalTime_IP
94  N30_d10_    1      1.000000
86  N30_d10_    2      1.000000
91  N30_d10_    3      1.000000
17  N30_d10_    4    402.949093
60  N30_d10_    5     80.062530
..       ...  ...           ...
52  N50_d10_   69    108.404747
12  N50_d10_   91    102.069724
33  N60_d10_   13  73844.104000
3   N60_d10_   16   3712.242432
85  N60_d10_   48    412.048270

[121 rows x 3 columns]

In [ ]:
location = "./LP_IP/"

#"./Documents/GitHub/UncertainTarget/EnumX_RowCol2ndStage/TestInstances/"
directory = os.fsencode(location)

# def importSet(filename, setRow, setLabel):
df_LP = pd.DataFrame(columns=('dataSet', 'ins','theta_LP', 'totalTime_LP', 't_RowGen_LP', 'n_RowGen_LP', 't_ColGen_LP','n_ColGen_LP'))
# location = "Documents/GitHub/UncertainTarget/EnumX_RowCol2ndStage/TestInstances/p_Instances_Output/"
allSets = []
k = 0
for file in os.listdir(directory):
    filename = os.fsdecode(file) 
#     print(filename)
    if filename.startswith('O_'):
        filePath = os.path.join(location, filename)
#         print(filePath)
        thisFile = open(filePath, "r")
          # remove /n at the end of each line
        lines_E = thisFile.readlines()
        thisFile.close()
        r = 0
        df_row = [0 for i in range(8)]
        for index, line in enumerate(lines_E):
            lines_E[index] = line.strip()
        for line in lines_E:
#             print(line)
            line = line.replace(', ', ',')
            line = line.replace('; ', ' ')
            elem = line.split(' = ')
            if elem[0] == "dataSet":
#                 
                df_row[0] = elem[1]
            elif elem[0] == "ins":
                df_row[1] = elem[1]
            elif elem[0] == "theta":
                df_row[2] = elem[1]
            elif elem[0] == "totalTime":
                df_row[3] = elem[1]
            elif elem[0] == "t_RowGen":
                df_row[4] = elem[1]
            elif elem[0] == "n_RowGen":
                df_row[5] = elem[1]
            elif elem[0] == "t_ColGen":
                df_row[6] = elem[1]
            elif elem[0] == "n_ColGen":
                df_row[7] = elem[1]
                        
#             r = r+1
#         print(df_row)
        k=k+1
        df_LP.loc[k] = df_row
for colName in ['ins','theta_LP', 'totalTime_LP', 't_RowGen_LP', 'n_RowGen_LP', 't_ColGen_LP','n_ColGen_LP']:
    df_LP[colName] = pd.to_numeric(df_LP[colName])
#         print(df_E)
# display(df_E.style.format({'RootOptGap': '{:,.1%}'.format}))
# display()
df_LP.loc[df_LP.totalTime_LP <= 3600, 'class'] = "E"
df_LP.loc[df_LP.totalTime_LP > 3600, 'class'] = "H"
df_LP

df_LP.groupby(['dataSet', 'class'], as_index=False).count()
# df_LP.groupby(['dataSet'], as_index=False).aggregate({'totalTime':np.average,'t_RowGen':np.average,'t_ColGen':np.average, 't_ColGen':np.average })
# df_LP

In [ ]:
location = "./LP_IP/"
df_Summary_SVI = pd.DataFrame()
df_Summary_SVI = df_SVI.groupby(['dataSet', 'class'], as_index=False).size().reset_index(name='counts')

df_less1 = pd.DataFrame(columns=['dataSet', 'ins'])
filename = "LessThanAMinutes_LPIP.txt"
filePath = os.path.join(location, filename)
#         print(filePath)
thisFile = open(filePath, "r")
  # remove /n at the end of each line
lines_E = thisFile.readlines()
thisFile.close()
k = 0
df_row = [0 for i in range(2)]
for index, line in enumerate(lines_E):
    lines_E[index] = line.strip()
#         if filename.startswith('O_N30_'):
#                 print(filename)
for line in lines_E:
#             if filename.startswith('O_N30_'):
#                 print(filename)
#     print(line)
    line = line.replace(' = ', ' ')
    line = line.replace('\t', ' ')
    elem = line.split(' ')
#     print(elem)
    df_row[0] = elem[1]
    df_row[1] = elem[3]
    k=k+1
#     print(df_row)
    df_less1.loc[k] = df_row
#df.groupby(['col1', 'col2']).size()
df_less1 = df_less1.groupby(['dataSet'],  as_index=False).size().reset_index(name='counts')
# df_Summary_SVI
df_less1

In [5]:
location = "./SVI/"

#"./Documents/GitHub/UncertainTarget/EnumX_RowCol2ndStage/TestInstances/"
directory = os.fsencode(location)

# df_SVI = 
# def importSet(filename, setRow, setLabel):
df_SVI = pd.DataFrame(columns=('dataSet', 'ins','theta_SVI', 'totalTime_SVI', 't_RowGen_SVI', 'n_RowGen_SVI', 't_ColGen_SVI','n_ColGen_SVI'))
# location = "Documents/GitHub/UncertainTarget/EnumX_RowCol2ndStage/TestInstances/p_Instances_Output/"
allSets = []
k = 0
for file in os.listdir(directory):
    filename = os.fsdecode(file) 
    
    if filename.startswith('O_N'):
        filePath = os.path.join(location, filename)
#         print(filePath)
        thisFile = open(filePath, "r")
          # remove /n at the end of each line
        lines_E = thisFile.readlines()
        thisFile.close()
        r = 0
        df_row = [0 for i in range(8)]
        for index, line in enumerate(lines_E):
            lines_E[index] = line.strip()
#         if filename.startswith('O_N30_'):
#                 print(filename)
        for line in lines_E:
#             if filename.startswith('O_N30_'):
#                 print(filename)
#                 print(line)
            line = line.replace(', ', ',')
            line = line.replace('; ', ' ')
            elem = line.split(' = ')
            if elem[0] == "dataSet":
                df_row[0] = elem[1]
            elif elem[0] == "ins":
                df_row[1] = elem[1]
            elif elem[0] == "theta":
                df_row[2] = elem[1]
            elif elem[0] == "totalTime":
#                 if filename.startswith('O_N30_'):
#                     print(elem[1])
                df_row[3] = elem[1]
            elif elem[0] == "t_RowGen":
                df_row[4] = elem[1]
            elif elem[0] == "n_RowGen":
                df_row[5] = elem[1]
            elif elem[0] == "t_ColGen":
                df_row[6] = elem[1]
            elif elem[0] == "n_ColGen":
                df_row[7] = elem[1]
                        
#             r = r+1
#         print(df_row)
        k=k+1
        df_SVI.loc[k] = df_row
for colName in ['ins','theta_SVI', 'totalTime_SVI', 't_RowGen_SVI', 'n_RowGen_SVI', 't_ColGen_SVI','n_ColGen_SVI']:
    df_SVI[colName] = pd.to_numeric(df_SVI[colName])
#         print(df_E)
# display(df_E.style.format({'RootOptGap': '{:,.1%}'.format}))
# display()

df_SVI.loc[df_SVI.totalTime_SVI <= 3600, 'class'] = "E"
df_SVI.loc[df_SVI.totalTime_SVI > 3600, 'class'] = "H"
df_SVI
# df_SVI[df_SVI['dataSet'] == 'N30_d10_']

df_SVI.groupby(['dataSet', 'class'], as_index=False).count()
# df_SVI.groupby(['dataSet', 'class'], as_index=False).aggregate({'totalTime_SVI':np.average,'t_RowGen_SVI':np.average,'t_ColGen_SVI':np.average, 't_ColGen_SVI':np.average })

,dataSet,class,ins,theta_SVI,totalTime_SVI,t_RowGen_SVI,n_RowGen_SVI,t_ColGen_SVI,n_ColGen_SVI
0,N30_d10_,E,47,47,47,47,47,47,47
1,N30_d10_,H,3,3,3,3,3,3,3
2,N40_d10_,E,7,7,7,7,7,7,7
3,N40_d10_,H,5,5,5,5,5,5,5
4,N50_d10_,E,1,1,1,1,1,1,1

In [6]:
location = "./SVI/"
df_Summary_SVI = pd.DataFrame()
df_Summary_SVI = df_SVI.groupby(['dataSet', 'class'], as_index=False).size().reset_index(name='counts')

df_less1 = pd.DataFrame(columns=['dataSet', 'ins'])
filename = "LessThanAMinutes_SVI.txt"
filePath = os.path.join(location, filename)
#         print(filePath)
thisFile = open(filePath, "r")
  # remove /n at the end of each line
lines_E = thisFile.readlines()
thisFile.close()
k = 0
df_row = [0 for i in range(2)]
for index, line in enumerate(lines_E):
    lines_E[index] = line.strip()
#         if filename.startswith('O_N30_'):
#                 print(filename)
for line in lines_E:
#             if filename.startswith('O_N30_'):
#                 print(filename)
#     print(line)
    line = line.replace(' = ', ' ')
    line = line.replace('\t', ' ')
    elem = line.split(' ')
#     print(elem)
    df_row[0] = elem[1]
    df_row[1] = elem[3]
    k=k+1
#     print(df_row)
    df_less1.loc[k] = df_row
df_less1['ins'] = pd.to_numeric(df_less1['ins'])
#df.groupby(['col1', 'col2']).size()
# df_less1 = df_less1.groupby(['dataSet'],  as_index=False).size().reset_index(name='counts')
# df_Summary_SVI
df_less1['totalTime_IP'] = 1
df_less1

df_time = df_IP[['dataSet', 'ins', 'totalTime_IP']].append(df_less1, ignore_index=True)
df_time= df_time.sort_values(by=['dataSet','ins'])
# df_time= df_time.sort_values(by=['ins'])
df_time

#df.groupby(['col1', 'col2']).size()
# df_less1 = df_less1.groupby(['dataSet'],  as_index=False).size().reset_index(name='counts')
# df_Summary_SVI
df_less1

    dataSet  counts
0  N30_d10_      48
1  N40_d10_       6

In [ ]:
new_df = pd.merge(df_IP, df_LP,  how='left', left_on=['dataSet','ins'], right_on = ['dataSet','ins'])
new_df = pd.merge(new_df, df_SVI,  how='left', left_on=['dataSet','ins'], right_on = ['dataSet','ins'])
# new_df['timerow_IP_LP'] = (new_df['t_RowGen_IP'] - new_df['t_RowGen_LP'])/new_df['t_RowGen_IP']
# new_df['timediff_IP_LP'] = (new_df['totalTime_IP'] - new_df['totalTime_LP'])/new_df['totalTime_IP']
# new_df['timerow_IP_SVI'] = (new_df['t_RowGen_IP'] - new_df['t_RowGen_SVI'])/new_df['t_RowGen_IP']
# new_df['timediff_IP_SVI'] = (new_df['totalTime_IP'] - new_df['totalTime_SVI'])/new_df['totalTime_IP']

new_df= new_df.sort_values(by=['dataSet', 'ins'])
# new_df.to_csv('./allOutputs.csv') 

# #Checking N30d10
# # new_df[new_df.dataSet == 'N30_d10_']['timediff_IP_SVI'].sum()
# new_df[['dataSet','n_RowGen_IP', 't_RowGen_IP','n_RowGen_LP','t_RowGen_LP','n_RowGen_SVI','t_RowGen_SVI']]
new_df[['dataSet','ins', 'totalTime_IP', 'totalTime_SVI']]

In [ ]:
new_df['weight_IP_LP'] = np.where(new_df.timerow_IP_LP.notnull(), 1, 0)
display(new_df.style.format({'timediff_IP_LP': '{:,.1%}'.format, 'timediff_IP_SVI': '{:,.1%}'.format,
                            'timerow_IP_LP': '{:,.1%}'.format, 'timerow_IP_SVI': '{:,.1%}'.format}))

In [ ]:
df_Summary1 = new_df.groupby(['dataSet', 'weight_IP_LP'], as_index=False).aggregate({'totalTime_IP':np.average, 'timerow_IP_LP':np.average,'timediff_IP_LP':np.average})#,'timecol_IP_SVI':np.average, 'timediff_IP_SVI':np.average })
df_Summary1 = df_Summary1.dropna()
df_Summary1 = df_Summary1.drop(['weight_IP_LP'], axis=1)
df_Summary1

In [ ]:
df_Summary2 = new_df.groupby(['dataSet'], as_index=False).aggregate({'totalTime_IP':np.average, 'timerow_IP_SVI':np.average,'timediff_IP_SVI':np.average})#,'timecol_IP_SVI':np.average, 'timediff_IP_SVI':np.average })
df_Summary2 = df_Summary2.drop(['totalTime_IP'], axis=1)
df_Summary2.dropna()
df_Summary2

In [ ]:
final_results = pd.merge(df_Summary1, df_Summary2,  how='left', left_on=['dataSet'], right_on = ['dataSet'])
final_results
display(final_results.style.format({'timediff_IP_LP': '{:,.1%}'.format, 'timediff_IP_SVI': '{:,.1%}'.format,
                            'timerow_IP_LP': '{:,.1%}'.format, 'timerow_IP_SVI': '{:,.1%}'.format}))